export enum ProductionControlHistoryAction {
  SNAPSHOT_CREATED = 'SNAPSHOT_CREATED',
  ORDER_CHECKED = 'ORDER_CHECKED',
  ORDER_UNCHECKED = 'ORDER_UNCHECKED',
  PRODUCT_CHECKED = 'PRODUCT_CHECKED',
  PRODUCT_UNCHECKED = 'PRODUCT_UNCHECKED',
  DATE_UPDATED = 'DATE_UPDATED',
  AUTO_COMPLETED = 'AUTO_COMPLETED',
}